# Generated by Django 2.2.22 on 2022-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned',
            name='currentprice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='owned',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
    ]
